"""gen_check_values.py -- regenerate the manual/tutorial CHECK VALUES from the
code, so the documents can never drift from the implementation.

Runs the four tutorial laminates through the actual homogenization and the
tutorial-1 recovery chain, then writes

    check_values.json    the machine-readable values (guarded by
                         tests/test_manual_check_values.py under the normal
                         pytest CI: if the code changes a number, the test
                         fails until this generator is re-run and the docs
                         rebuilt)
    check_values.tex     the LaTeX table the manual \\input s

Run:  python docs/rm_plate_manual/gen_check_values.py

Variables
---------
CASES        the four tutorial laminates (material db + layup + fraction),
             EXACTLY as printed in the tutorial document
vals         {case: {"D11": ..., "G11": ...}} + the tutorial-1 recovery
             anchors (mid-thickness s13, the s33 top-face closure)
"""
import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
CC = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, CC)

from opensg_jax.fe_jax.msg_rm_plate import rm_plate_msg, msgrm_strain_at_depth  # noqa: E402

H_GARG = 0.1
CASES = {
    "tut1_caseA": dict(
        db={"pagano": {"E": [25.0e9, 1.0e9, 1.0e9], "G": [0.5e9, 0.5e9, 0.2e9],
                       "nu": [0.25, 0.25, 0.25], "rho": 1.0}},
        layup={"mat_names": ["pagano"] * 3, "thick": [H_GARG / 3] * 3,
               "angles": [0.0, 90.0, 0.0]}, fraction=0.5,
        label="Tut.~1 cross-ply $[0/90/0]$, $S{=}10$"),
    "tut2_sandwich": dict(
        db={"face": {"E": [131.0e9, 10.34e9, 10.34e9],
                     "G": [6.205e9, 6.205e9, 3.0e9],
                     "nu": [0.22, 0.22, 0.22], "rho": 1.0},
            "core": {"E": [0.5776e9] * 3, "G": [0.1079e9] * 3,
                     "nu": [0.0025] * 3, "rho": 1.0}},
        layup={"mat_names": ["face", "core", "face"],
               "thick": [0.1 * H_GARG, 0.8 * H_GARG, 0.1 * H_GARG],
               "angles": [0.0, 0.0, 0.0]}, fraction=0.5,
        label="Tut.~2 sandwich $[0/\\mathrm{core}/0]$, $S{=}10$"),
    "tut3_yu15": dict(
        db={"yu": {"E": [25.0e6, 1.0e6, 1.0e6], "G": [0.5e6, 0.5e6, 0.2e6],
                   "nu": [0.25, 0.25, 0.25], "rho": 1.0}},
        layup={"mat_names": ["yu"] * 2, "thick": [0.5, 0.5],
               "angles": [15.0, -15.0]}, fraction=0.5,
        label="Tut.~3 $[15/-15]$, $L/h{=}4$ (psi--in)"),
    "tut4_yu30": dict(
        db={"yu": {"E": [25.0e6, 1.0e6, 1.0e6], "G": [0.5e6, 0.5e6, 0.2e6],
                   "nu": [0.25, 0.25, 0.25], "rho": 1.0}},
        layup={"mat_names": ["yu"] * 4, "thick": [0.25] * 4,
               "angles": [30.0, -30.0, -30.0, 30.0]}, fraction=0.5,
        label="Tut.~4 $[30/-30/-30/30]$, $L/h{=}4$ (psi--in)"),
}


def compute():
    """All check values (the dict written to JSON)."""
    vals = {}
    for name, c in CASES.items():
        lay = c["layup"]
        r = rm_plate_msg(lay["thick"], lay["angles"], lay["mat_names"],
                         c["db"], fraction=c["fraction"])
        A = np.asarray(r["ABDG"])
        vals[name] = {"D11": float(A[3, 3]), "G11": float(A[6, 6]),
                      "A11": float(A[0, 0]), "label": c["label"]}
    # tutorial-1 recovery anchors (the exact chain printed in the tutorial)
    c = CASES["tut1_caseA"]; lay = c["layup"]
    r = rm_plate_msg(lay["thick"], lay["angles"], lay["mat_names"], c["db"],
                     fraction=0.5)
    a, q0, h = 1.0, 1.0e4, H_GARG
    p = np.pi / a
    S6 = np.linalg.inv(np.asarray(r["A6"]))
    dE1 = S6 @ np.array([0, 0, 0, q0 / p, 0, 0.0])
    qt6 = np.array([0, p * q0, 0, 0, 0, 0.0])
    z = np.linspace(-h / 2 + 1e-9, h / 2 - 1e-9, 201)
    s13 = np.array([msgrm_strain_at_depth(r, zi, np.zeros(6), dE1,
                                          qt6=qt6)[1][4] for zi in z])
    s33 = np.concatenate([[0.0], np.cumsum(0.5 * p * (s13[1:] + s13[:-1])
                                           * np.diff(z))])
    vals["tut1_recovery"] = {"s13_mid": float(s13[100]),
                             "s33_top_closure": float(s33[-1] / q0)}
    return vals


def write(vals):
    """Write check_values.json + the LaTeX table check_values.tex."""
    with open(os.path.join(HERE, "check_values.json"), "w") as f:
        json.dump(vals, f, indent=1)
    L = ["% AUTO-GENERATED by gen_check_values.py -- do not edit by hand",
         "\\begin{center}\\begin{tabular}{lccc}", "\\toprule",
         "tutorial laminate & $A_{11}$ & $D_{11}$ & $G_{11}$ \\\\", "\\midrule"]
    for name in ("tut1_caseA", "tut2_sandwich", "tut3_yu15", "tut4_yu30"):
        v = vals[name]
        L.append("%s & %.4e & %.4e & %.4e \\\\"
                 % (v["label"], v["A11"], v["D11"], v["G11"]))
    rec = vals["tut1_recovery"]
    L += ["\\midrule",
          "\\multicolumn{4}{l}{Tut.~1 recovery anchors: "
          "$\\sigma_{13}(0)=%.1f$~Pa,\\ \\ $\\sigma_{33}$ top closure $=%.4f\\,q_0$}\\\\"
          % (rec["s13_mid"], rec["s33_top_closure"]),
          "\\bottomrule", "\\end{tabular}\\end{center}"]
    with open(os.path.join(HERE, "check_values.tex"), "w") as f:
        f.write("\n".join(L) + "\n")


if __name__ == "__main__":
    v = compute()
    write(v)
    for name in ("tut1_caseA", "tut2_sandwich", "tut3_yu15", "tut4_yu30"):
        print("%-14s D11 %.4e  G11 %.4e" % (name, v[name]["D11"],
                                            v[name]["G11"]))
    print("tut1 recovery: s13_mid %.1f, s33 closure %.4f"
          % (v["tut1_recovery"]["s13_mid"],
             v["tut1_recovery"]["s33_top_closure"]))
